package com.scyy.domain;
// Generated 2016-9-27 10:04:24 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer userid;
	private String username;
	private String name;
	private String password;
	private Date adddate;
	private Date editdate;
	private String editwho;
	private String job;
	private Double feed;
	private String corp;
	private Integer type;
	private Integer pos;
	private Integer depid;

	public Users() {
	}

	public Users(String username, String name, String password, Date adddate, Date editdate, String editwho, String job,
			Double feed, String corp, Integer type, Integer pos, Integer depid) {
		this.username = username;
		this.name = name;
		this.password = password;
		this.adddate = adddate;
		this.editdate = editdate;
		this.editwho = editwho;
		this.job = job;
		this.feed = feed;
		this.corp = corp;
		this.type = type;
		this.pos = pos;
		this.depid = depid;
	}

	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getAdddate() {
		return this.adddate;
	}

	public void setAdddate(Date adddate) {
		this.adddate = adddate;
	}

	public Date getEditdate() {
		return this.editdate;
	}

	public void setEditdate(Date editdate) {
		this.editdate = editdate;
	}

	public String getEditwho() {
		return this.editwho;
	}

	public void setEditwho(String editwho) {
		this.editwho = editwho;
	}

	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	public Double getFeed() {
		return this.feed;
	}

	public void setFeed(Double feed) {
		this.feed = feed;
	}

	public String getCorp() {
		return this.corp;
	}

	public void setCorp(String corp) {
		this.corp = corp;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Integer getPos() {
		return this.pos;
	}

	public void setPos(Integer pos) {
		this.pos = pos;
	}

	public Integer getDepid() {
		return this.depid;
	}

	public void setDepid(Integer depid) {
		this.depid = depid;
	}

}
